#!/bin/bash

cp -r ~/Themes/Cozy/. ~/ &&
wal -b 282738 -i ~/Wallpaper/Aesthetic2.png &&
#~/.spicetify/spicetify apply &&

cat > ~/.config/gtk-3.0/settings.ini <<EOF
[Settings]
gtk-theme-name=Cozy-clean
gtk-icon-theme-name=Cozy_Icons_blue
gtk-font-name=JetBrains Mono 10
EOF

#pkill flameshot && flameshot &
pkill dunst && dunst &
qtile cmd-obj -o cmd -f restart
