#!/bin/bash

cp -r ~/Themes/Everforest/. ~/ &&
wal -b 232A2E -i Wallpaper/fog_forest_2.png &&
#~/.spicetify/spicetify apply &&

cat > ~/.config/gtk-3.0/settings.ini <<EOF
[Settings]
gtk-theme-name=Everforest-Yellow-Dark
gtk-icon-theme-name=Everforest-Icons-Cool
gtk-font-name=JetBrains Mono 10
EOF

#pkill flameshot && flameshot &
pkill dunst && dunst
qtile cmd-obj -o cmd -f restart
