#!/bin/bash

cp -r ~/Themes/Natura/. ~/ &&
wal -i ~/Wallpaper/claudio-testa-FrlCwXwbwkk-unsplash.jpg &&
#~/.spicetify/spicetify apply &&

cat > ~/.config/gtk-3.0/settings.ini <<EOF
[Settings]
gtk-theme-name=Natura-Clean
gtk-icon-theme-name=Natura-Icons
gtk-font-name=JetBrains Mono 10
EOF

#pkill flameshot && flameshot &
pkill dunst && dunst
qtile cmd-obj -o cmd -f restart
